name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
    - name: Set up Docker Buildx
      run: docker buildx create --use
    - name: Build the Docker image
      run: docker buildx build --platform linux/amd64 -t seefood-backend .
    - name: Push to DockerHub
      run: docker push ${{secrets.DOCKER_USER}}/seefood-backend

